[project]
name = "generosity-actions"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2",
    "pandas>=2.2",
    "numexpr>=2.10",
    "bottleneck>=1.4",
    "memo-lang>=1.2.9",
]
